
import type { NavItem, Activity, Notification, User } from "@/lib/types";
import {
  LayoutDashboard,
  ClipboardList,
  BarChart3,
  Users,
  Settings,
  ShieldAlert,
  Syringe,
  UserCheck,
  Bell,
  MessageSquare,
  FileCheck2,
  AlertTriangle,
  Info,
  Palette,
  Database,
  HelpCircle,
  User as UserIcon,
  PlusCircle,
  List,
  Calendar,
  FileText,
  TrendingUp,
  Map,
  CheckCircle,
  Clock,
} from "lucide-react";

export const navItems: NavItem[] = [
  {
    title: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
  },
  {
    title: "Activities",
    href: "/dashboard/activities",
    icon: ClipboardList,
    badge: 5,
  },
  {
    title: "Reports",
    href: "/dashboard/reports",
    icon: BarChart3,
  },
  {
    title: "Team",
    href: "/dashboard/team",
    icon: Users,
  },
  {
    title: 'Notifications',
    href: '/dashboard/notifications',
    icon: Bell,
    badge: 3
  },
  {
    title: "Profile",
    href: "/dashboard/profile",
    icon: UserCheck,
  },
  {
    title: "Settings",
    href: "/dashboard/settings",
    icon: Settings
  },
];

export const federalDashboardMetrics = [
  {
    title: "Total Activities",
    value: "1,247",
    trend: "+12% this month",
    icon: ClipboardList,
    accentColor: "bg-primary",
    trendColor: "text-green-500",
  },
  {
    title: "Active Outbreaks",
    value: "3",
    trend: "2 under control, 1 active",
    icon: ShieldAlert,
    accentColor: "bg-orange-500",
  },
  {
    title: "Vaccination Coverage",
    value: "67.3%",
    trend: "Target: 70%",
    icon: Syringe,
    accentColor: "bg-green-500",
    progress: 67.3,
  },
  {
    title: "Workers Trained",
    value: "15,892",
    trend: "↑ 1,234 this quarter",
    icon: UserCheck,
    accentColor: "bg-accent",
    trendColor: "text-accent"
  },
];

export const stateDashboardMetrics = [
  {
    title: "State Activities",
    value: "182",
    trend: "+8% this month",
    icon: ClipboardList,
    accentColor: "bg-primary",
    trendColor: "text-green-500",
  },
  {
    title: "LGAs Covered",
    value: "18 / 20",
    trend: "90% coverage",
    icon: Map,
    accentColor: "bg-blue-500",
    progress: 90,
  },
  {
    title: "Pending Approvals",
    value: "12",
    trend: "3 overdue",
    icon: Clock,
    accentColor: "bg-orange-500",
  },
  {
    title: "State Field Workers",
    value: "1,240",
    trend: "↑ 50 new this quarter",
    icon: Users,
    accentColor: "bg-accent",
    trendColor: "text-accent"
  },
];

export const lgaDashboardMetrics = [
  {
    title: "My Assigned Activities",
    value: "8",
    trend: "3 starting this week",
    icon: ClipboardList,
    accentColor: "bg-primary",
  },
  {
    title: "Completed this Month",
    value: "12",
    trend: "On track with target",
    icon: CheckCircle,
    accentColor: "bg-green-500",
  },
  {
    title: "Pending Reports",
    value: "3",
    trend: "1 overdue",
    icon: FileText,
    accentColor: "bg-orange-500",
  },
   {
    title: "My Team Members",
    value: "5",
    trend: "In Ikeja LGA",
    icon: Users,
    accentColor: "bg-accent",
  },
];

export const performanceChartData = [
    { date: 'Jan', created: 45, completed: 30 },
    { date: 'Feb', created: 55, completed: 42 },
    { date: 'Mar', created: 70, completed: 60 },
    { date: 'Apr', created: 65, completed: 55 },
    { date: 'May', created: 80, completed: 70 },
    { date: 'Jun', created: 75, completed: 68 },
];

export const activityTypeChartData = [
  { name: 'Vaccination', value: 400, fill: 'hsl(var(--chart-1))' },
  { name: 'Health Ed', value: 300, fill: 'hsl(var(--chart-2))' },
  { name: 'Outreach', value: 250, fill: 'hsl(var(--chart-3))' },
  { name: 'Training', value: 200, fill: 'hsl(var(--chart-4))' },
  { name: 'Surveillance', value: 150, fill: 'hsl(var(--chart-5))' },
];

export const mockActivities: Activity[] = [
    {
        id: "ACT-001",
        title: "COVID-19 Vaccination Campaign - Phase 3",
        status: "Approved",
        organization: "Lagos State Health Department",
        location: "Lagos, Ikeja LGA",
        dateCreated: "2025-10-01",
        lastModified: "2025-12-01",
        description: "Third phase of the statewide COVID-19 vaccination drive.",
        type: "Vaccination Campaign",
    },
    {
        id: "ACT-002",
        title: "Cholera Prevention Training Workshop",
        status: "Submitted",
        organization: "Federal MOH",
        location: "Abuja FCT, Municipal Area Council",
        dateCreated: "2025-11-05",
        lastModified: "2025-11-06",
        description: "Training workshop for healthcare workers on cholera prevention and control.",
        type: "Training Workshop",
    },
    {
        id: "ACT-003",
        title: "Community Health Education - Malaria Prevention",
        status: "Approved",
        organization: "Rivers State MOH",
        location: "Rivers, Port Harcourt",
        dateCreated: "2025-09-15",
        lastModified: "2025-09-20",
        description: "Educating communities on malaria prevention methods.",
        type: "Health Education",
    },
    {
        id: "ACT-004",
        title: "Emergency Response - Lassa Fever Outbreak",
        status: "Submitted",
        organization: "Oyo State MOH",
        location: "Oyo, Ibadan North",
        dateCreated: "2025-12-10",
        lastModified: "2025-12-10",
        description: "Rapid response to a reported Lassa Fever outbreak.",
        type: "Emergency Response",
    },
    {
        id: "ACT-005",
        title: "Routine Immunization Campaign",
        status: "Draft",
        organization: "Kano State PHCDA",
        location: "Kano, Kano Municipal",
        dateCreated: "2025-12-12",
        lastModified: "2025-12-12",
        description: "Planning for the next routine immunization cycle.",
        type: "Immunization",
    },
    {
        id: "ACT-006",
        title: "Disease Surveillance Training",
        status: "Rejected",
        organization: "Oyo State MOH",
        location: "Oyo, Ibadan South-West",
        dateCreated: "2025-11-20",
        lastModified: "2025-11-22",
        description: "Proposal for disease surveillance training, rejected due to budget issues.",
        type: "Training Workshop",
    },
    {
        id: "ACT-007",
        title: "Hand Hygiene Awareness Program",
        status: "Completed",
        organization: "Lagos State Health Department",
        location: "Lagos, Epe",
        dateCreated: "2025-08-01",
        lastModified: "2025-08-30",
        description: "A month-long campaign in schools to promote handwashing.",
        type: "Health Education",
    },
    {
        id: "ACT-008",
        title: "Distribution of Insecticide-Treated Nets",
        status: "Approved",
        organization: "Rivers State MOH",
        location: "Rivers, Bonny",
        dateCreated: "2025-10-05",
        lastModified: "2025-10-10",
        description: "Distribution of ITNs to households in high-risk areas.",
        type: "Outreach",
    },
    {
        id: "ACT-009",
        title: "Polio Vaccination Drive - Kano",
        status: "Completed",
        organization: "Kano State PHCDA",
        location: "Kano, Dala",
        dateCreated: "2025-07-15",
        lastModified: "2025-08-15",
        description: "State-wide polio vaccination for children under 5.",
        type: "Vaccination Campaign",
    },
    {
        id: "ACT-010",
        title: "Public Health Seminar: Non-communicable Diseases",
        status: "Submitted",
        organization: "Federal MOH",
        location: "Abuja FCT, Gwagwalada",
        dateCreated: "2025-12-01",
        lastModified: "2025-12-01",
        description: "A seminar for the general public on preventing NCDs like diabetes and hypertension.",
        type: "Health Education",
    },
    {
        id: "ACT-011",
        title: "Data Management Training for Health Officials",
        status: "Approved",
        organization: "Federal MOH",
        location: "Abuja FCT, Municipal Area Council",
        dateCreated: "2025-09-01",
        lastModified: "2025-09-10",
        description: "Training on using the new RCAP platform for data entry and analysis.",
        type: "Training Workshop",
    },
    {
        id: "ACT-012",
        title: "Maternal Health Workshop",
        status: "Draft",
        organization: "Lagos State Health Department",
        location: "Lagos, Ikorodu",
        dateCreated: "2025-12-15",
        lastModified: "2025-12-15",
        description: "A workshop focused on improving maternal and child health outcomes.",
        type: "Training Workshop",
    },
    {
        id: "ACT-013",
        title: "Measles Vaccination Campaign - Oyo",
        status: "Approved",
        organization: "Oyo State MOH",
        location: "Oyo, Akinyele",
        dateCreated: "2025-10-20",
        lastModified: "2025-10-25",
        description: "Targeted measles vaccination for children in underserved communities.",
        type: "Vaccination Campaign",
    },
    {
        id: "ACT-014",
        title: "Water Sanitation Project Monitoring",
        status: "Completed",
        organization: "Rivers State MOH",
        location: "Rivers, Okrika",
        dateCreated: "2025-06-01",
        lastModified: "2025-07-01",
        description: "Monitoring and evaluation of new borehole projects to ensure water safety.",
        type: "Surveillance",
    },
    {
        id: "ACT-015",
        title: "Nutrition counseling for mothers",
        status: "Submitted",
        organization: "Kano State PHCDA",
        location: "Kano, Nassarawa",
        dateCreated: "2025-11-28",
        lastModified: "2025-11-28",
        description: "Providing nutritional advice and support for pregnant and lactating mothers.",
        type: "Outreach",
    },
    {
        id: "ACT-016",
        title: "Review of National Health Policy",
        status: "Draft",
        organization: "Federal MOH",
        location: "Abuja FCT, Municipal Area Council",
        dateCreated: "2025-12-20",
        lastModified: "2025-12-20",
        description: "Internal review of the existing national health policy.",
        type: "Policy Review",
    }
];

export const mockNotifications: Notification[] = [
  {
    id: "NOTIF-001",
    type: "Approval",
    title: "Activity Approved",
    description: "Your activity 'Cholera Prevention Training Workshop' has been approved.",
    timestamp: "2025-12-11T10:00:00Z",
    isRead: false,
    icon: FileCheck2,
    iconColor: "text-green-500"
  },
  {
    id: "NOTIF-002",
    type: "Assignment",
    title: "New Task Assigned",
    description: "You have been assigned to 'Emergency Response - Lassa Fever Outbreak'.",
    timestamp: "2025-12-10T14:30:00Z",
    isRead: false,
    icon: FileCheck2,
    iconColor: "text-blue-500"
  },
  {
    id: "NOTIF-003",
    type: "Alert",
    title: "Urgent: Outbreak Alert",
    description: "A new Cholera outbreak has been reported in Kano State.",
    timestamp: "2025-12-10T09:00:00Z",
    isRead: false,
    icon: AlertTriangle,
    iconColor: "text-red-500"
  },
  {
    id: "NOTIF-004",
    type: "System",
    title: "System Update",
    description: "RCAP has been updated to version 1.1.0.",
    timestamp: "2025-12-09T18:00:00Z",
    isRead: true,
    icon: Info,
    iconColor: "text-primary"
  },
  {
    id: "NOTIF-005",
    type: "Comment",
    title: "New Comment",
    description: "Dr. Aisha added a comment on 'COVID-19 Vaccination Campaign'.",
    timestamp: "2025-12-08T11:45:00Z",
    isRead: true,
    icon: MessageSquare,
    iconColor: "text-gray-500"
  },
];

export const mockTeamMembers: User[] = [
    {
        id: 'USR-001',
        name: 'Dr. Amina Yusuf',
        email: 'amina.yusuf@rcap.gov',
        avatarId: 'user1',
        role: 'National Coordinator',
        team: 'Federal MOH',
        status: 'Active',
    },
    {
        id: 'USR-002',
        name: 'Bolanle Adebayo',
        email: 'bolanle.adebayo@rcap.gov',
        avatarId: 'user2',
        role: 'State Coordinator',
        team: 'Lagos State MOH',
        status: 'Active',
    },
    {
        id: 'USR-003',
        name: 'Chinedu Okoro',
        email: 'chinedu.okoro@rcap.gov',
        avatarId: 'user3',
        role: 'Field Officer',
        team: 'Rivers State MOH',
        status: 'Active',
    },
    {
        id: 'USR-004',
        name: 'Fatima Bello',
        email: 'fatima.bello@rcap.gov',
        avatarId: 'user4',
        role: 'Data Analyst',
        team: 'Federal MOH',
        status: 'Active',
    },
    {
        id: 'USR-005',
        name: 'Musa Ibrahim',
        email: 'musa.ibrahim@rcap.gov',
        avatarId: 'user5',
        role: 'State Coordinator',
        team: 'Kano State PHCDA',
        status: 'Active',
    },
    {
        id: 'USR-006',
        name: 'Ngozi Eze',
        email: 'ngozi.eze@rcap.gov',
        avatarId: 'user6',
        role: 'Field Officer',
        team: 'Oyo State MOH',
        status: 'Invited',
    },
    {
        id: 'USR-007',
        name: 'David Akpan',
        email: 'david.akpan@rcap.gov',
        avatarId: 'user7',
        role: 'Data Analyst',
        team: 'Lagos State MOH',
        status: 'Active',
    },
    {
        id: 'USR-008',
        name: 'Blessing Nwosu',
        email: 'blessing.nwosu@rcap.gov',
        avatarId: 'user8',
        role: 'Field Officer',
        team: 'Federal MOH',
        status: 'Active',
    },
    {
        id: 'USR-009',
        name: 'Sani Mohammed',
        email: 'sani.mohammed@rcap.gov',
        avatarId: 'user9',
        role: 'Field Officer',
        team: 'Kano State PHCDA',
        status: 'Active',
    },
    {
        id: 'USR-010',
        name: 'Titi Olawole',
        email: 'titi.olawole@rcap.gov',
        avatarId: 'user10',
        role: 'Epidemiologist',
        team: 'Federal MOH',
        status: 'Active',
    },
    {
        id: 'USR-011',
        name: 'Emeka Okafor',
        email: 'emeka.okafor@rcap.gov',
        avatarId: 'user11',
        role: 'Logistics Manager',
        team: 'Rivers State MOH',
        status: 'Active',
    },
    {
        id: 'USR-012',
        name: 'Halima Abubakar',
        email: 'halima.abubakar@rcap.gov',
        avatarId: 'user12',
        role: 'Communications Officer',
        team: 'Federal MOH',
        status: 'Active',
    },
    {
        id: 'USR-013',
        name: 'Yemi Ayodele',
        email: 'yemi.ayodele@rcap.gov',
        avatarId: 'user13',
        role: 'State Coordinator',
        team: 'Oyo State MOH',
        status: 'Invited',
    },
    {
        id: 'USR-014',
        name: 'Ibrahim Diallo',
        email: 'ibrahim.diallo@rcap.gov',
        avatarId: 'user14',
        role: 'IT Support',
        team: 'Federal MOH',
        status: 'Active',
    },
    {
        id: 'USR-015',
        name: 'Zainab Lawal',
        email: 'zainab.lawal@rcap.gov',
        avatarId: 'user15',
        role: 'Accountant',
        team: 'Federal MOH',
        status: 'Active',
    },
    {
        id: 'USR-016',
        name: 'Femi Johnson',
        email: 'femi.johnson@rcap.gov',
        avatarId: 'user16',
        role: 'Field Officer',
        team: 'Lagos State MOH',
        status: 'Active',
    },
        {
        id: 'USR-017',
        name: 'Aisha Musa',
        email: 'aisha.musa@rcap.gov',
        avatarId: 'user1',
        role: 'Field Officer',
        team: 'Kaduna State MOH',
        status: 'Active',
    },
    {
        id: 'USR-018',
        name: 'Olamide Adekunle',
        email: 'olamide.adekunle@rcap.gov',
        avatarId: 'user2',
        role: 'Data Analyst',
        team: 'Oyo State MOH',
        status: 'Active',
    },
    {
        id: 'USR-019',
        name: 'Ikenna Obi',
        email: 'ikenna.obi@rcap.gov',
        avatarId: 'user3',
        role: 'Field Officer',
        team: 'Anambra State MOH',
        status: 'Invited',
    },
    {
        id: 'USR-020',
        name: 'Hadiza Goje',
        email: 'hadiza.goje@rcap.gov',
        avatarId: 'user4',
        role: 'Communications Officer',
        team: 'Kano State PHCDA',
        status: 'Active',
    },
    {
        id: 'USR-021',
        name: 'Rotimi Williams',
        email: 'rotimi.williams@rcap.gov',
        avatarId: 'user5',
        role: 'Logistics Manager',
        team: 'Lagos State MOH',
        status: 'Active',
    },
    {
        id: 'USR-022',
        name: 'Chinelo Nwankwo',
        email: 'chinelo.nwankwo@rcap.gov',
        avatarId: 'user6',
        role: 'Epidemiologist',
        team: 'Federal MOH',
        status: 'Active',
    },
    {
        id: 'USR-023',
        name: 'Bello Garba',
        email: 'bello.garba@rcap.gov',
        avatarId: 'user7',
        role: 'State Coordinator',
        team: 'Kaduna State MOH',
        status: 'Active',
    },
    {
        id: 'USR-024',
        name: 'Funmilayo Adeboye',
        email: 'funmilayo.adeboye@rcap.gov',
        avatarId: 'user8',
        role: 'Accountant',
        team: 'Federal MOH',
        status: 'Active',
    },
    {
        id: 'USR-025',
        name: 'Efe Ajayi',
        email: 'efe.ajayi@rcap.gov',
        avatarId: 'user9',
        role: 'Field Officer',
        team: 'Edo State MOH',
        status: 'Active',
    },
    {
        id: 'USR-026',
        name: 'Abubakar Sadiq',
        email: 'abubakar.sadiq@rcap.gov',
        avatarId: 'user10',
        role: 'IT Support',
        team: 'Federal MOH',
        status: 'Invited',
    },
];

export const reportActivityTrendsWeek = [
    { period: 'Week 1', activities: '85 activities', date: 'Jan 1-7', progress: 85 },
    { period: 'Week 2', activities: '92 activities', date: 'Jan 8-14', progress: 92 },
    { period: 'Week 3', activities: '78 activities', date: 'Jan 15-21', progress: 78 },
    { period: 'Week 4', activities: '95 activities', date: 'Jan 22-28', progress: 95 },
];

export const reportActivityTrendsMonth = [
    { period: 'January', activities: '340 activities', date: 'Month view', progress: 85 },
    { period: 'February', activities: '368 activities', date: 'Month view', progress: 92 },
    { period: 'March', activities: '312 activities', date: 'Month view', progress: 78 },
    { period: 'April', activities: '380 activities', date: 'Month view', progress: 95 },
];

export const reportActivityTrendsYear = [
    { period: '2023', activities: '4080 activities', date: 'Year view', progress: 85 },
    { period: '2024', activities: '4416 activities', date: 'Year view', progress: 92 },
    { period: '2025', activities: '3744 activities', date: 'Year view', progress: 78 },
];


export const reportActivityTypes = [
    { name: 'Vaccination Campaign', count: 342, colorClass: 'bg-chart-1' },
    { name: 'Health Education', count: 256, colorClass: 'bg-chart-2' },
    { name: 'Emergency Response', count: 189, colorClass: 'bg-chart-3' },
    { name: 'Training Workshop', count: 145, colorClass: 'bg-chart-4' },
    { name: 'Disease Surveillance', count: 71, colorClass: 'bg-chart-5' },
];

export const reportStatusBreakdown = [
    { name: 'Approved', count: 572, description: '↑ 12% vs last month', borderColor: 'hsl(var(--primary))' },
    { name: 'Submitted', count: 134, description: 'Pending review', borderColor: 'hsl(var(--accent))' },
    { name: 'Draft', count: 89, description: 'In progress', borderColor: 'hsl(var(--muted))' },
    { name: 'Rejected', count: 24, description: 'Needs revision', borderColor: 'hsl(var(--destructive))' },
];

export const reportGeographicDistribution = [
    { name: 'Lagos', count: 342, colorClass: 'bg-chart-1' },
    { name: 'Kano', count: 218, colorClass: 'bg-chart-1' },
    { name: 'Rivers', count: 156, colorClass: 'bg-chart-2' },
    { name: 'Kaduna', count: 134, colorClass: 'bg-chart-2' },
    { name: 'FCT Abuja', count: 98, colorClass: 'bg-chart-3' },
    { name: 'Oyo', count: 87, colorClass: 'bg-chart-3' },
    { name: 'Edo', count: 76, colorClass: 'bg-chart-4' },
    { name: 'Others', count: 136, colorClass: 'bg-chart-5' },
];

export const reportTemplates = [
    { id: 'weekly-summary', name: 'Weekly Summary', description: 'A snapshot of the week\'s performance.', icon: Calendar },
    { id: 'monthly-report', name: 'Monthly Report', description: 'A comprehensive monthly review.', icon: FileText },
    { id: 'performance-analysis', name: 'Performance Analysis', description: 'Deep-dive into activity trends.', icon: TrendingUp },
];
